### ISSUE TITLE
синтаксическая ошибка в слове

### ISSUE THREAD

**Issue by AzatGo** [prasx/HelpDesk#1]
строка 229:    text = f'🎉🥳 Успех, ваша заявка зарегестрирована! \n\n<b>Номер заявки: </b><code>#{last_ticket_number}</code>. \n\n<i>PS: Отслеживайте статус поставленных задач в разделе</i> <b>"📥 Мои заявки"</b>'

ошибка в слове, должно быть "зарегистрирована"

**Comment by prasx** [comment]
[AzatGo](https://github.com/AzatGo), спасибо!)
Текст в новой версии изменил. Спасибо за бдительность 👍
